config/routes.rb
Rails.application.routes.draw do

  get 'doses/create'

  get 'doses/destroy'

   resources :cocktails do
     resources :doses, only: [ :create]
   end 
    resources :doses, only: :destroy

   root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader

  def safe_photo
    if photo.present?
      photo
    else
      ""
    end
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, :cocktail_id, :ingredient_id, presence: true
  belongs_to :ingredient
  belongs_to :cocktail
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @doses = Dose.where(cocktail: set_cocktail)
    @dose = Dose.new
    @ingredients = Ingredient.order(:name).all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end


  private
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
     params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    @dose.ingredient = Ingredient.find(params[:dose][:ingredient_id])

     respond_to do |format|
      if @dose.save
        format.html { redirect_to @dose.cocktail, notice: 'Dose was successfully added to Cocktail.' }
        format.json { render :show, status: :created, location: @dose }
      else
        format.html { redirect_to @dose.cocktail }
        format.json { render json: @dose.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to @dose.cocktail
  end


  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.safe_photo %>');">
  <%= link_to "#{cocktail.name}", cocktail_path(cocktail), {class: "card-title"} %>

</div>

app/views/cocktails/_dose_form.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :ingredient_id, collection: @ingredients, prompt: "Choose an ingredient" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, {class: "btn btn-primary", id:"form-button"} %>
  </div>
<% end %>

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, {class: "btn btn-primary", id:"form-button"} %>
  </div>
<% end %>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<%= render 'shared/home-banner' %>

<div class="wrapper">
  <div class="my-container">
    <h2>All cocktails</h2>

      <div class="cards">
        <% @cocktails.each do |cocktail| %>
          <%= render 'card', cocktail: cocktail %>
        <% end %>

      </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="wrapper">
  <div class="my-container">
    <h2>Add new cocktail</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="wrapper">
  <div class="my-container">
    <h1 class="cocktail-title"><%= @cocktail.name.upcase %></h1>
    <%= cl_image_tag @cocktail.photo, height: 200, width: 800, crop: :fill, class: "banner-image" %>
    <br>
      <div class="dose-container">
        <h3>How to make this cocktail...</h3>
         <%= link_to "Delete cocktail?", cocktail_path(@cocktail),
          method: :delete,
          data: { confirm: "Are you sure?" } %>


          <% @doses.each do |dose| %>
          <p class="dose-text"><%= "#{dose.description} #{dose.ingredient.name}" %></p>
          <% end %>
      </div>


          <div class="dose-form">
            <h4>Add an ingredient and description of dose</h4>
            <%= render 'dose_form' %>
          </div>




  </div>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,700|Spectral+SC" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'  %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
   <p> Drink responsibly!</p>
  </div>
</div>

app/views/shared/_home-banner.html.erb
<div class="flex-two-col">
  <div class="flex-left">
    <%= cl_image_tag("cocktails.png", {class: "hp-image"}) %>
  </div>
  <div class="flex-right">
    <h1>Cocktail Lovers</h1>
    <h2>The only place to find the best cocktail recipes and create your own. </h2>
    <%= link_to 'Create new cocktail here', new_cocktail_path,{class: "btn btn-primary", id: "home-banner-button"} %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav-left">
  <%= cl_image_tag("cocktail-logo.png", :width=>50, :crop=>"scale")%>
      <%= link_to 'Cocktail lovers', cocktails_path, {class: "logo-small"} %>
  </div>
  <div class= "nav-right">
    <%= link_to 'View all', cocktails_path %>
    <%= link_to 'Add cocktail', new_cocktail_path %>
  </div>
</nav>